<?php

class BusinessVerificationType
{
    const BASIC_BUSINESS_REGISTRATION = "BASIC_BUSINESS_REGISTRATION";
    const BUSINESS_REGISTRATION = "BUSINESS_REGISTRATION";
    const TAX_INFORMATION = "TAX_INFORMATION";
    const ALL = array(self::BASIC_BUSINESS_REGISTRATION, self::BUSINESS_REGISTRATION, self::TAX_INFORMATION);
}
